services:
  todo-api:
    build: .
    ports:
      - "8002:8002"
      - "5679:5679"  # Add debug port
    volumes:
    - ..:/app:cached
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
